export const NoLicense = 'No \nLicense'
export const ExpiredLicense =  'Expired \nLicense'
export const InvalidDocument =  'Fake \nDocument'
export const DirivingUnderInfluence =  'Driving Under \n Influence'
export const NoProperGear =  'No Proper \nattire '
export const SpeedingVehicle =  'Speeding'
export const RecklessDriving =  'Reckless Driving'
export const ObsturctionVehicle =  'Obstruction \nof Road'
export const RegistrationRelated =  'Not \nRegistered'
export const ORCRrelated =  'OR CR \nExpired'
export const Others =  ''
export const version = 'Traffic Violation Management (Beta)'
export const consent  = "By filling out and submitting this citation ticket, The Apprehended affirm that all of the information provided is true and accurate to the best of their knowledge. Any false, misleading, or incomplete information may result in additional fines, legal consequences, or the suspension or revocation of their license. The Officer is responsible for maintaining the confidentiality of any personal information and for securing their device to anyone. The Apprehended accept responsibility for all activities that occur under their name or personal information. If they believe that their personal information has been compromised, it is their obligation to notify the issuing agency as soon as possible."
export const about = "BSCS A  is a development team that specializes in creating custom software solutions for businesses of all sizes. Our team is made up of experienced developers who are skilled in a variety of programming languages and technologies. \n\nWe pride ourselves on our ability to understand our clients' needs and deliver high-quality, reliable software that meets their specific requirements. Whether you are looking to build a web application, mobile app, or software program, we have the expertise to bring your vision to life. \n\nAt BSCS A , we believe in building long-term partnerships with our clients. We take the time to understand your business, your goals, and your challenges, and we work closely with you to develop a solution that meets your needs and exceeds your expectations. \n\nWhether you are a startup looking to bring your product to market or a well-established company looking to improve your existing software, BSCS A has the experience and expertise to help you succeed. We look forward to working with you and helping you achieve your business objectives."